<a href="https://colab.research.google.com/github/prafulacharya/Data_Analyst/blob/main/Python_Data_Analyst.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Analyzing Numerical Data with NumPy

Creating NumPy Array #dimentions-->Rank 

In [ ]:
import numpy as np
#create an array with 4 elements
b = np.empty(4, dtype = int)
print("Matrix b : \n", b)

#create an array with 2*2 rank 
a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)
   
c = np.empty([3, 3])
print("\nMatrix c : \n", c)

#if your using multiple print statement then use "\n" for line space

Matrix b : 
 [4607182418800017408 4607182418800017408 4607182418800017408
                   0]

Matrix a : 
 [[    34928192 459561500672]
 [433791697012            0]]
[[1.5952194e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


 Create Array using numpy.zeros , 1D, 2D, 3D

In [ ]:
import numpy as np
   
b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)

#1D array -
x=np.array([1,2,3,4])
print(x)
#2D array - 
y=np.array([[1,2],[3,4]])
print(y.shape[0])
#3D array
z=np.array([
            [[1,2],[3,4]],
            [[4,5],[6,7]],
            [[8,9],[10,11]]
            ])
print(z)
   


Matrix b : 
 [0 0]
[1 2 3 4]
2
[[[ 1  2]
  [ 3  4]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


Operations on Numpy Arrays

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([6,7,8,9])
print("\nAddtion:", a+b)
print(np.add(a,b))

import numpy as np
  
# Defining both the matrices
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])
  
# Performing addition using arithmetic operator
add_ans = a+b
print(add_ans)
  
# Performing addition using numpy function
add_ans = np.add(a, b)
print(add_ans)


Addtion: [ 7  9 11 13]
[ 7  9 11 13]
[  7  77  23 130]
[  7  77  23 130]


NumPy Array Indexing

In [ ]:
# Python program to demonstrate 
# the use of index arrays.
import numpy as np
   
# Create a sequence of integers from
# 10 to 1 with a step of -2
a = np.arange(10, 1, -2) 
print("\n A sequential array with a negative step: \n",a)
   
# Indexes are specified inside the np.array method.
newarr = a[np.array([3, 1, 2 ])]
print("\n Elements at these indices are:\n",newarr)


 A sequential array with a negative step: 
 [10  8  6  4  2]

 Elements at these indices are:
 [4 8 6]


NumPy Array Slicing

In [ ]:

# Python program for basic slicing.
import numpy as np
  
# Arrange elements from 0 to 19
a = np.arange(20)
print("\n Array is:\n ",a)
  
# a[start:stop:step]
print("\n a[-8:17:1] = ",a[-8:17:1])
  
# The : operator means all elements till the end.
print("\n a[10:] = ",a[10:])


 Array is:
  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1] =  [12 13 14 15 16]

 a[10:] =  [10 11 12 13 14 15 16 17 18 19]


Ellipsis can also be used along with basic slicing. 

In [ ]:
# Python program for indexing using basic slicing with ellipsis
import numpy as np
  
# A 3 dimensional array.
b = np.array([[[1, 2, 3],[4, 5, 6]],
            [[7, 8, 9],[10, 11, 12]]])
  
print(b[...,1])

[[ 2  5]
 [ 8 11]]


NumPy Array Broadcasting

#Shape- Number of elements in each dimentions

In [ ]:
a=np.zeros([1,3])
print(a)
print(a.shape)

[[0. 0. 0.]]
(1, 3)


Analyzing Data using Pandas

#Pandas generally provide two data structures for manipulating data, 
Series -Pandas Series is a one-dimensional labelled array  capable of holding data of any type (integer, string, float, python objects. Pandas Series is nothing but a column in an excel sheet.
Dataframe -  A Data frame is a two-dimensional data structure, i.e., data is aligned in a tabular fashion in rows and columns.

In [ ]:
#Creating a series 
import pandas as pd
import numpy as np
  
  
# Creating empty series
ser = pd.Series()
  
print(ser)
  
# simple array
data = np.array(['g', 'e', 'e', 'k', 's'])
  
ser = pd.Series(data)
print(ser)

Series([], dtype: float64)
0    g
1    e
2    e
3    k
4    s
dtype: object


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  import sys


In [ ]:
#Creating DataFrame
import pandas as pd
  
# Calling DataFrame constructor
df = pd.DataFrame()
print(df)
  
# list of strings
lst = ['Geeks', 'For', 'Geeks', 'is',
            'portal', 'for', 'Geeks']
  
# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
df

##Filter data/csv file based on colums usinf filter function 
#df.filter(["Species", "SepalLengthCm", "SepalLengthCm"]).head()


## applying filter function
#df.sort_values(by=['SepalLengthCm'])

Empty DataFrame
Columns: []
Index: []


0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

Pandas GroupBy

Splitting: It is a process in which we split data into group by applying some conditions on datasets.
Applying: It is a process in which we apply a function to each group independently.
Combining: It is a process in which we combine different datasets after applying groupby and results into a data structure.

In [ ]:
# importing pandas module
import pandas as pd
  
# Define a dictionary containing employee data
data1 = {'Name': ['Jai', 'Anuj', 'Jai', 'Princi',
                  'Gaurav', 'Anuj', 'Princi', 'Abhi'],
         'Age': [27, 24, 22, 32,
                 33, 36, 27, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                     'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd',
                           'B.Tech', 'B.com', 'Msc', 'MA']}
  
# Convert the dictionary into DataFrame
df = pd.DataFrame(data1)
  
print("Original Dataframe")
display(df)
  
# applying groupby() function to
# group the data on Name value.
gk = df.groupby('Name')
  
# Let's print the first entries
# in all the groups formed.
print("After Creating Groups")
gk.first()

Original Dataframe


Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1    Anuj   24     Kanpur            MA
2     Jai   22  Allahabad           MCA
3  Princi   32    Kannuaj           Phd
4  Gaurav   33    Jaunpur        B.Tech
5    Anuj   36     Kanpur         B.com
6  Princi   27  Allahabad           Msc
7    Abhi   32    Aligarh            MA

After Creating Groups


Age  Address Qualification
Name                              
Abhi     32  Aligarh            MA
Anuj     24   Kanpur            MA
Gaurav   33  Jaunpur        B.Tech
Jai      27   Nagpur           Msc
Princi   32  Kannuaj           Phd

Pandas Aggregation
df = pd.DataFrame(data1)
  
# performing aggregation using
# aggregate method
  
grp1 = df.groupby('Name')
  
grp1.aggregate(np.sum)



Merging DataFrame -  merge() -
Joins can only be done on two DataFrames at a time, denoted as left and right tables


In [ ]:
# importing pandas module
import pandas as pd 
   
# Define a dictionary containing employee data 
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32],} 
     
# Define a dictionary containing employee data 
data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']} 
   
# Convert the dictionary into DataFrame  
df = pd.DataFrame(data1)
   
# Convert the dictionary into DataFrame  
df1 = pd.DataFrame(data2) 
    
  
display(df, df1) 
  
# using .merge() function
res = pd.merge(df, df1, on='key')
   
res

# joining dataframe
#res = df.join(df1)

Visualization with Matplotlib

Pyplot

Pyplot provides functions that interact with the figure

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
  
df = pd.read_csv("Iris.csv")
  
# This will plot a simple bar,histogram, scatter chart
plt.bar(df['Species'], df['SepalLengthCm'])
plt.hist(df["SepalLengthCm"])
plt.scatter(df["Species"], df["SepalLengthCm"])
  
# Title to the plot
plt.title("Iris Dataset")
  
# Adding the legends
plt.legend(["bar"])
plt.show()